; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=xtensa -mattr=+windowed %s -o - | FileCheck %s

; Verify that when a dynamic stack allocation is present, any subsequent
; stack argument setups around calls (ADJCALLSTACKDOWN) preserve the
; 16-byte stack pointer alignment required by the Windowed ABI.

declare void @ext(i32, i32, i32, i32, i32, i32, i32)

define void @test_alloca(i32 %n) {
; CHECK-LABEL: test_alloca:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    entry a1, 48
; CHECK-NEXT:    or a7, a1, a1
; CHECK-NEXT:    addi a8, a2, 15
; CHECK-NEXT:    movi a9, -16
; CHECK-NEXT:    and a8, a8, a9
; CHECK-NEXT:    sub a8, a1, a8
; CHECK-NEXT:    movsp a1, a8
; CHECK-NEXT:    addi a8, a1, -16
; CHECK-NEXT:    movsp a1, a8
; CHECK-NEXT:    movi a8, 7
; CHECK-NEXT:    s32i a8, a1, 0
; CHECK-NEXT:    movi a10, 1
; CHECK-NEXT:    movi a11, 2
; CHECK-NEXT:    movi a12, 3
; CHECK-NEXT:    movi a13, 4
; CHECK-NEXT:    movi a14, 5
; CHECK-NEXT:    movi a15, 6
; CHECK-NEXT:    l32r a8, .LCPI0_0
; CHECK-NEXT:    callx8 a8
; CHECK-NEXT:    addi a8, a1, 16
; CHECK-NEXT:    movsp a1, a8
; CHECK-NEXT:    retw
entry:

  %0 = alloca i8, i32 %n, align 16


  ; Make a call with 7 arguments (28 bytes). The 7th argument goes on the stack.
  ; ADJCALLSTACKDOWN must align the 4 bytes to 16 bytes, decrementing sp by 16, not 4.
  call void @ext(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7)


  ret void
}
