; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=xtensa -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Test placement of the i32,i64, float and double constants in constantpool

define dso_local i32 @const_i32() #0 {
; CHECK-LABEL: const_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a8, a1, -16
; CHECK-NEXT:    or a1, a8, a8
; CHECK-NEXT:    l32r a2, .LCPI0_0
; CHECK-NEXT:    s32i a2, a1, 12
; CHECK-NEXT:    addi a8, a1, 16
; CHECK-NEXT:    or a1, a8, a8
; CHECK-NEXT:    ret
  %1 = alloca i32, align 4
  store i32 74565, ptr %1, align 4
  %2 = load i32, ptr %1, align 4
  ret i32 %2
}

define dso_local i64 @const_int64() #0 {
; CHECK-LABEL: const_int64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a8, a1, -16
; CHECK-NEXT:    or a1, a8, a8
; CHECK-NEXT:    l32r a3, .LCPI1_0
; CHECK-NEXT:    s32i a3, a1, 12
; CHECK-NEXT:    l32r a2, .LCPI1_1
; CHECK-NEXT:    s32i a2, a1, 8
; CHECK-NEXT:    addi a8, a1, 16
; CHECK-NEXT:    or a1, a8, a8
; CHECK-NEXT:    ret
  %1 = alloca i64, align 8
  store i64 1311768467302729063, ptr %1, align 8
  %2 = load i64, ptr %1, align 8
  ret i64 %2
}
