; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=xtensa -disable-block-placement -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

define ptr @test_simple_alloca(i32 %numelts) {
; CHECK-LABEL: test_simple_alloca:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a8, a1, -16
; CHECK-NEXT:    or a1, a8, a8
; CHECK-NEXT:    s32i a15, a1, 12 # 4-byte Folded Spill
; CHECK-NEXT:    or a15, a1, a1
; CHECK-NEXT:    addi a8, a2, 15
; CHECK-NEXT:    movi a9, -16
; CHECK-NEXT:    and a8, a8, a9
; CHECK-NEXT:    addi a8, a8, 31
; CHECK-NEXT:    movi a9, -32
; CHECK-NEXT:    and a8, a8, a9
; CHECK-NEXT:    sub a1, a1, a8
; CHECK-NEXT:    or a2, a1, a1
; CHECK-NEXT:    or a1, a15, a15
; CHECK-NEXT:    l32i a15, a1, 12 # 4-byte Folded Reload
; CHECK-NEXT:    addi a8, a1, 16
; CHECK-NEXT:    or a1, a8, a8
; CHECK-NEXT:    ret

  %addr = alloca i8, i32 %numelts
  ret ptr %addr
}
