; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; NOTE: Assertions are stubs - run utils/update_llc_test_checks.py to populate
; RUN: llc -mtriple=xtensa -mattr=+windowed,+hifi4 %s -o - | FileCheck %s

; Test copyPhysReg for HiFi AE register classes
; Covers: [Xtensa] CodeGen InstrInfo: HiFi copyPhysReg and windowed adjustStackPtr fix

; A function that uses an AE register via intrinsic and forces a copy
; through a function call boundary (triggering spill/restore logic)
declare void @use_ae_reg()

define void @test_hifi_copyphysreg() {
; CHECK-LABEL: test_hifi_copyphysreg:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    entry a1, 48
; CHECK-NEXT:    l32r a8, .LCPI0_0
; CHECK-NEXT:    callx8 a8
; CHECK-NEXT:    retw
entry:
  call void @use_ae_reg()
  ret void
}
