; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=xtensa < %s | FileCheck %s

define { ptr, i32 } @test() personality ptr null {
; CHECK-LABEL: test:
; CHECK:       .Lfunc_begin0:
; CHECK-NEXT:  # %bb.0: # %else
; CHECK-NEXT:    addi a8, a1, -16
; CHECK-NEXT:    or a1, a8, a8
; CHECK-NEXT:    s32i a0, a1, 12 # 4-byte Folded Spill
; CHECK-NEXT:    movi a2, 0
; CHECK-NEXT:    or a3, a2, a2
; CHECK-NEXT:    or a4, a2, a2
; CHECK-NEXT:    callx0 a2
else:
  invoke void null({ i32, ptr } zeroinitializer, i32 0)
          to label %postinvoke unwind label %landingPad

postinvoke:
  unreachable

landingPad:
  %0 = landingpad { ptr, i32 }
          cleanup
  ret { ptr, i32 } %0
}
