; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=xtensa -function-sections --mcpu=esp32 --filetype=obj < %s\
; RUN: | llvm-objdump -r -s --triple=xtensa --mcpu=esp32 - | FileCheck %s

; CHECK-LABEL: Contents of section .literal.func.literal:
; CHECK:       0000 88130000                             ....

define i32 @func() {
  ret i32 5000
}
