; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; NOTE: Assertions are stubs - run utils/update_llc_test_checks.py to populate
; RUN: llc -mtriple=xtensa -mattr=+windowed %s -o - | FileCheck %s

; Test FrameLowering and RegisterInfo windowed ABI fixes:
; - Stack alignment (4-byte with 8-byte ENTRY rounding)
; - MOV_N usage when Density is available
; - hasReservedCallFrame behaviour
; - Register scavenging in eliminateFrameIndex
; Covers: [Xtensa] CodeGen FrameLowering and RegisterInfo: windowed ABI, register scavenging

declare void @ext(i32)

; Function with a large stack frame to exercise register scavenging
define void @test_large_frame(i32 %n) {
; CHECK-LABEL: test_large_frame:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    entry a1, 1064
; CHECK-NEXT:    addi a8, a1, 4
; CHECK-NEXT:    addx4 a8, a2, a8
; CHECK-NEXT:    l32i.n a10, a8, 0
; CHECK-NEXT:    l32r a8, .LCPI0_0
; CHECK-NEXT:    callx8 a8
; CHECK-NEXT:    retw.n
entry:
  ; Allocate a large fixed array to force a large frame index offset
  %buf = alloca [256 x i32], align 4
  %ptr = getelementptr [256 x i32], [256 x i32]* %buf, i32 0, i32 %n
  %val = load i32, i32* %ptr
  call void @ext(i32 %val)
  ret void
}

; Small leaf function - should use minimal stack
define i32 @test_leaf(i32 %a, i32 %b) {
; CHECK-LABEL: test_leaf:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    entry a1, 40
; CHECK-NEXT:    add.n a2, a2, a3
; CHECK-NEXT:    retw.n
entry:
  %sum = add i32 %a, %b
  ret i32 %sum
}
